Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y build-essential python-dev python-matplotlib python-pip build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev libxml2-dev  libxml2 libxml2-dev libxslt-dev zlib1g-dev  libxml2-dev libxmlsec1-dev
    sudo pip install --upgrade jinja2 tornado jsonschema pyzmq BeautifulSoup4 html5lib lxml pandas
  SHELL

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    ipython notebook --notebook-dir=/vagrant --no-browser --ip=0.0.0.0 &
  SHELL

end



# sudo easy_install greenlet
# sudo easy_install gevent

# let's start ipython notebook
# ipython notebook --ip=0.0.0.0 # port-forwarding doesn't work without this --ip flag
# IPython Notebook now accessible on http://localhost:8888/ on the host

#    sudo apt-get update
#    sudo apt-get install -y python3-pip python-matplotlib libxml2-dev python3-lxml ipython ipython-notebook
#    sudo pip3 install --upgrade ipython[all]
#    sudo pip3 install pandas
#    sudo pip3 install lxml
#    sudo pip3 install html5lib
#    sudo pip3 install BeautifulSoup4
